spring.application.name=tool

# MYSQL
spring.datasource.url=jdbc:mysql://localhost:3306/tool_db
spring.datasource.username=root
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# EMAIL CONFIG (GMAIL)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=manjunewofficial12@gmail.com
spring.mail.password=rgnd raao nsyw vsxn
app.email.to=manjunewofficial12@gmail.com

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

file.upload-dir=uploads